apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: qa
  namespace: argocd

spec:
  description: QA environment

  sourceRepos:
    - https://github.com/mad8555/login-service-gitops.git

  destinations:
    - namespace: qa
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
