apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: login-service
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
      - env: qa
      - env: prod

  template:
    metadata:
      name: login-service-{{env}}
    spec:
      project: default

      source:
        repoURL: https://github.com/mad8555/login-service-gitops.git
        targetRevision: HEAD
        path: overlays/{{env}}

      destination:
        server: https://kubernetes.default.svc
        namespace: login-service-{{env}}

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
