apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
spec:
  template:
    spec:
      containers:
      - name: login-service
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
